project:
  type: website
  output-dir: docs
  resources:
    - libs/
  render:
    - index.qmd
    - slides/
    
website:
  title: "Penyusunan Tes Kognitif"
  repo-url: https://github.com/rameliaz/ptk
  repo-actions: [edit, source, issue]  
  repo-branch: master  
  sidebar:
    style: docked
    contents:
      - text: "Beranda"
        href: index.qmd
      - section: "Materi 🇮🇩"
        contents:
          - text: "Pertemuan 1: Pengantar: Pengertian dan Jenis Tes Kognitif"
            href: slides/pertemuan1.qmd
          - text: "Pertemuan 2: Tahap Penyusunan Tes Kognitif"
            href: slides/pertemuan2.qmd
          - text: "Pertemuan 3: Taksonomi dan Tujuan Instruksional"
            href: slides/pertemuan3.qmd
          - text: "Pertemuan 4: Pengertian dan Tujuan Tes Prestasi"
            href: slides/pertemuan4.qmd
          - text: "Pertemuan 5: Tes Potensi"
            href: slides/pertemuan5.qmd
          - text: "Pertemuan 6: Tes Intelegensi"
            href: slides/pertemuan6.qmd
          - text: "Pertemuan 7: Menulis Item Tes Prestasi dan Potensi"
            href: slides/pertemuan7.qmd
          - text: "Pertemuan 9: Menulis Item HOTS"
            href: slides/pertemuan9.qmd
          - text: "Pertemuan 15: Isu Bias Budaya dalam Penyusunan Tes Kognitif"
            href: slides/pertemuan15.qmd
      - section: "Materi 🇬🇧"
        contents:
          - text: "1. Introduction: Definition and Types of Cognitive Tests"
            href: slides/pertemuan1-en.qmd
          - text: "2. Stages of Cognitive Test Development"
            href: slides/pertemuan2-en.qmd
          - text: "3. Taxonomy and Instructional Objectives"
            href: slides/pertemuan3-en.qmd
          - text: "4. Definition and Purpose of Achievement Tests"
            href: slides/pertemuan4-en.qmd
          - text: "5. Aptitude Tests"
            href: slides/pertemuan5-en.qmd
          - text: "6. Intelligence Tests"
            href: slides/pertemuan6-en.qmd
          - text: "7. Writing Achievement and Aptitude Test Items"
            href: slides/pertemuan7-en.qmd
          - text: "9. Writing HOTS Items"
            href: slides/pertemuan9-en.qmd
          - text: "15. Cultural Bias Issues in Cognitive Test Development"
            href: slides/pertemuan15-en.qmd
  navbar:
    left:
      - href: https://psikologi.unair.ac.id/dosen-rizqy-amelia-zein/
        icon: house-heart
        text: "oleh Rizqy Amelia Zein"
    tools:
      - icon: github
        menu: 
          - text: "Source Code"
            href: https://github.com/rameliaz/ptk
          - text: "Report Issues"
            href: https://github.com/rameliaz/ptk/issues
      - icon: house-heart
        url: https://rameliaz.github.io/            
      - icon: envelope
        href: "mailto:amelia.zein@psikologi.unair.ac.id"
  search:
    location: navbar
    type: overlay
  page-footer:
      left: |
        Laman web dibuat dengan [![](https://quarto.org/quarto.png){fig-alt="Quarto" width=65px}](https://quarto.org/)
      center: |
        <a class="link-dark me-1" href="https://github.com/rameliaz" title="github" target="_blank" rel="noopener"><i class="fa-brands fa-github"></i></a>
        <a class="link-dark me-1" href="mailto:amelia.zein@psikologi.unair.ac.id" title="Email" target="_blank" rel="noopener"><i class="fa-solid fa-envelope"></i></a>
        <a class="link-dark me-1" href="https://bsky.app/profile/ameliazein.bsky.social" title="Bluesky" target="_blank" rel="noopener"><i class="fa-brands fa-bluesky"></i></a>
        <a class="link-dark me-1" href="https://discord.com/users/807046335613632555" title="Discord" target="_blank" rel="noopener"><i class="fa-brands fa-discord"></i></a>
      right: | 
         &#169; 2026 Rizqy Amelia Zein \ 
         \ S1 Psikologi, Universitas Airlangga
format:
  html:
    theme:
      light: sandstone
      dark: slate
    toc: true
    toc-float: true
    toc-depth: 3
    df-print: paged
    highlight-style: github
